import "./globals.css";
import { Navigation } from "./components/Navigation";

// export const metadata = {
//   title: "My First Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>My first Next 14 app</title>
      </head>
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
